### ISSUE TITLE
Patch to correct bug in classes/tools/s3/ilab-media-s3-tool.php

### ISSUE THREAD

**Issue by TBarregren** [jawngee/ILab-Media-Tools#1]
Patch: [classes_tools_s3_ilab-media-s3-tool.php.diff.zip](https://github.com/jawngee/ILab-Media-Tools/files/434353/classes_tools_s3_ilab-media-s3-tool.php.diff.zip)

For details, see [https://wordpress.org/support/topic/s3-importer-got-stuck](https://wordpress.org/support/topic/s3-importer-got-stuck).

**Comment by jawngee** [comment]
Thanks for this!

It's been committed in 4982e51883d18061799050ccd4a58664e333ba9a
