### ISSUE TITLE
S3 Upload hangs with missing Key Error

### ISSUE THREAD

**Issue by ihilt** [jawngee/ILab-Media-Tools#2]
Sanitized stack trace

`2016/11/19 10:49:49 [error] 3947#3947: *73 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: Found 2 errors while validating the input provided for the PutObject operation:
[Key] is missing and is a required parameter
[Key] expected string length to be >= 1, but found string length of 0 in /srv/www/example.com/releases/20161118173652/web/app/plugins/ilab-media-tools/vendor/aws/aws-sdk-php/src/Api/Validator.php:65
Stack trace:
#0 /srv/www/example.com/releases/20161118173652/web/app/plugins/ilab-media-tools/vendor/aws/aws-sdk-php/src/Middleware.php(79): ILAB_Aws\Api\Validator->validate('PutObject', Object(ILAB_Aws\Api\StructureShape), Array)
#1 /srv/www/example.com/releases/20161118173652/web/app/plugins/ilab-media-tools/vendor/aws/aws-sdk-php/src/S3/S3Client.php(354): ILAB_Aws\Middleware::ILAB_Aws\{closure}(Object(ILAB_Aws\Command), NULL)
#2 /srv/www/example.com/releases/20161118173652/web/app/plugins/ilab-media-tools/vendor/aws/aws-sdk-php/src/S3/S3Client.php(377): ILAB_Aws\S3\S3Client::ILAB_Aws\S3\{" while reading response header from upstream, client: 123.123.123.123, server: example.com, request: "POST /wp/wp-admin/admin-ajax.php?action=wp_ilab_s3_import_process&nonce=837c4a6558 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-wordpress.sock:", host: "example.com", referrer: "http://example.com/wp/wp-admin/admin-ajax.php?action=wp_ilab_s3_import_process&nonce=837c4a6558"`

I don't understand why it's complaining about a key because it is set and it successfully transferred a couple files. I'm on WP 4.6.1 and php 7.0 on ubuntu 16.04.1.

**Comment by jawngee** [comment]
What was the original filename, do you know?

**Comment by ihilt** [comment]
Sorry, no I don't. Are there specific characters that WordPress would allow but the Amazon importer wouldn't?

**Comment by jawngee** [comment]
To be honest, I haven't really used the importer functionality, but on regular uploads I've not seen the issue.  We use the plugin on 5-6 sites at this point and it's never been an issue we've heard about from clients.

That being said, I'll give this some more thorough testing over the weekend.

Sorry it took so long to get to this, been busy!
