### ISSUE TITLE
Focal Point support?

### ISSUE THREAD

**Issue by stursby** [jawngee/ILab-Media-Tools#4]
First off, I just wanted to thank you for this Plugin, it's *amazing*.

So I was wondering if you had any thoughts for supporting the [Imgix Focal Point Crop](https://docs.imgix.com/apis/url/focalpoint-crop) in this Plugin?

**Comment by jawngee** [comment]
I didn't know that option existed until now.   Would be great to add though.  Will add to the todo list.

Thanks!

**Comment by stursby** [comment]
Awesome  🙌   Anything I can help with?
