### ISSUE TITLE
Tag New Version?

### ISSUE THREAD

**Issue by JulienMelissas** [jawngee/ILab-Media-Tools#5]
First of all - thanks for this. Looks amazing and I'm really excited to be able to start working with it! 
I'm using Bedrock which uses composer to install plugins. Would you mind tagging a new release with your new version when you get a chance so I can set an exact version? Thanks!

**Comment by jawngee** [comment]
Use this one:

https://github.com/interfacelab/ilab-media-tools/

I should kill this one but I have some client sites using it as a submodule.

**Comment by jawngee** [comment]
For composer:

composer require ilab/ilab-media-tools

Thanks!!

**Comment by JulienMelissas** [comment]
Word. Thanks!
